import { Vehicle } from './Vehicle';

export const VEHICLES: Vehicle[] = [
  {
    id: 1,
    title: 'Mercedes-Benz',
    image: '/assets/imgs/car-placeholder.png',
    city: 'Islamabad',
    price: 100000,
    dateAdded: new Date(),
    rating: 4,
    make: 'Mercedes-Benz',
    year: 2014,
    mileage: 50000,
    color: 'Black',
    engine: 'V8',
    type: 'Car'
  },
  {
    id: 2,
    title: 'BMW X6',
    image: '/assets/imgs/car-placeholder.png',
    city: 'Karachi',
    price: 120000,
    dateAdded: new Date(),
    rating: 5,
    make: 'BMW',
    year: 2016,
    mileage: 60000,
    color: 'Black',
    engine: 'V8',
    type: 'Car'
  },
  {
    id: 3,
    title: 'Audi A8',
    image: '/assets/imgs/car-placeholder.png',
    city: 'Faisalabad',
    price: 150000,
    dateAdded: new Date(),
    rating: 3,
    make: 'Audi',
    year: 2015,
    mileage: 70000,
    color: 'Black',
    engine: 'V8',
    type: 'Car'
  },
  {
    id: 4,
    title: 'Ford F-150',
    image: '/assets/imgs/car-placeholder.png',
    city: 'Multan',
    price: 200000,
    dateAdded: new Date(),
    rating: 4,
    make: 'Ford',
    year: 2017,
    mileage: 80000,
    color: 'Black',
    engine: 'V8',
    type: 'Car'
  },
  {
    id: 5,
    title: 'Chevrolet Silverado',
    image: '/assets/imgs/car-placeholder.png',
    city: 'Lahore',
    price: 250000,
    dateAdded: new Date(),
    rating: 5,
    make: 'Chevrolet',
    year: 2018,
    mileage: 90000,
    color: 'Black',
    engine: 'V8',
    type: 'Car'
  },
  {
    id: 6,
    title: 'Honda Civic',
    image: '/assets/imgs/car-placeholder.png',
    city: 'Karachi',
    price: 300000,
    dateAdded: new Date(),
    rating: 4,
    make: 'Honda',
    year: 2019,
    mileage: 100000,
    color: 'Black',
    engine: 'V8',
    type: 'Car'
  },
  {
    id: 7,
    title: 'Toyota Corolla',
    image: '/assets/imgs/car-placeholder.png',
    city: 'Islamabad',
    price: 350000,
    dateAdded: new Date(),
    rating: 5,
    make: 'Toyota',
    year: 2016,
    mileage: 110000,
    color: 'Black',
    engine: 'V8',
    type: 'Car'
  },
  {
    id: 8,
    title: 'Nissan Altima',
    image: '/assets/imgs/car-placeholder.png',
    city: 'Islamabad',
    price: 400000,
    dateAdded: new Date(),
    rating: 3,
    make: 'Nissan',
    year: 2019,
    mileage: 120000,
    color: 'Black',
    engine: 'V8',
    type: 'Car'
  }
];